version: "3.8"

volumes:
  postgres-data:
  redis-data:
  
networks:
  net:

services:
  bot:
    container_name: bot-nlp-search
    build: ..
    env_file:
      - ../.env
    restart: always
    depends_on:
      - redis
    networks:
      - net

  redis:
    container_name: redis-nlp-search
    image: redis:6.2-alpine
    env_file:
      - ../.env
    volumes:
      - redis-data:/data
    restart: always
    ports:
      - "6379:6379"
    networks:
      - net
